export {
  mdiArrowLeft,
  mdiArrowRight,
  mdiBell,
  mdiClose,
  mdiCodeTags,
  mdiCog,
  mdiDotsVertical,
  mdiImage,
  mdiLoading,
  mdiLockOpenAlert,
  mdiMenu,
  mdiPartyPopper,
  mdiPencil,
  mdiRefresh,
  mdiTab,
  mdiTabPlus,
  mdiToggleSwitch,
  mdiToggleSwitchOff,
  mdiUnfoldMoreHorizontal,
  mdiUnfoldLessHorizontal,
} from '@mdi/js';
